# Generated by Django 4.1.7 on 2023-12-29 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0003_labscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='labscore',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
    ]
