# Generated by Django 4.1.7 on 2023-12-08 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0002_alter_category_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='videomodel',
            name='labs_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='labs.labtypemodel'),
        ),
    ]
