# Generated by Django 4.1.7 on 2023-12-10 12:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('labs', '0003_labtypemodel_videomodel_labs_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='videomodel',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='video_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
